name: ROC - CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: ROC - CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install & lint
        working-directory: ./
        run: |
          yarn install --frozen-lockfile
          yarn lint
